#!/usr/bin/env bash

/home/dschumacher/dschumacher_working_dir/anaconda/envs/NMTGMinor_env_python3_6/bin/python3.6 preprocess.py \
-train_src /home/dschumacher/dschumacher_working_dir/preprocessing/after_preprocessing/papers_arxiv_own/category_computer_science/preproc_cleanLowTokenize_2018_11_08_17_27_41/splits/training_source_preproc_source_summaries.txt \
-train_tgt /home/dschumacher/dschumacher_working_dir/preprocessing/after_preprocessing/papers_arxiv_own/category_computer_science/preproc_cleanLowTokenize_2018_11_08_17_27_41/splits/training_target_preproc_target_titles.txt \
-valid_src /home/dschumacher/dschumacher_working_dir/preprocessing/after_preprocessing/papers_arxiv_own/category_computer_science/preproc_cleanLowTokenize_2018_11_08_17_27_41/splits/validation_source_preproc_source_summaries.txt \
-valid_tgt /home/dschumacher/dschumacher_working_dir/preprocessing/after_preprocessing/papers_arxiv_own/category_computer_science/preproc_cleanLowTokenize_2018_11_08_17_27_41/splits/validation_target_preproc_target_titles.txt \
-save_data /home/dschumacher/dschumacher_working_dir/preprocessing/after_preprocessing/papers_arxiv_own/category_computer_science/transformer_preproc_no_bpe_2018_11_15  \
-format raw \
-src_seq_length 512 \
-tgt_seq_length 256
